name: pilltime
description: A medication reminder app for people with chronic illnesses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  
  # State Management and Data Persistence
  shared_preferences: ^2.2.2
  
  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  #assets:
    #- assets/images/
    #- assets/icons/
  
  # Fonts
  